import os
from dotenv import load_dotenv

load_dotenv()

# Env variables
TELEGRAM_BOT_TOKEN=os.getenv('TELEGRAM_BOT_TOKEN')
MORALIS_API_KEY=os.getenv('MORALIS_API_KEY')
REWARD_ACCOUNT=os.getenv('REWARD_ACCOUNT')
TAX_ACCOUNT=os.getenv('TAX_ACCOUNT')
PURCHASED_RPC=os.getenv('PURCHASED_RPC')
PURCHASED_WSS=os.getenv('PURCHASED_WSS')
BOT_NAME=os.getenv('BOT_NAME')
BOT_USER_NAME=os.getenv('BOT_USER_NAME')
DOG_SCANNER_BOT=os.getenv('DOG_SCANNER_BOT')

# Global Constants
LAMPORTS_PER_SOL = 1e9
WSOL = 'So11111111111111111111111111111111111111112'
USDT = 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB'
USDC = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
ADMIN = "3LXCueEeCqbGyoyYbdZicWeHKFfycdL2FMuFoFVbD8kA"
TRANSFER_MIN_SOL_LIMIT = 5100
DOGBOT = ''
TOKEN_PROGRAM_ID = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
TOKEN_2022_PROGRAM_ID = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
TOKEN_MAPPING = {
    'So11111111111111111111111111111111111111112': {'name': 'Wrapped SOL', 'symbol':'SOL'},
    'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB': {'name': 'USDT', 'symbol':'USDT'},
    'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v': {'name': 'USD Coin', 'symbol':'USDC'},
}
PRIORITY_MAPPING = {
    "LOW": 1,
    1: "LOW",
    "STANDARD": 2,
    2: "STANDARD",
    "HIGH": 3,
    3: "HIGH",
}
RAYDIUM_LIQUIDITY_POOL_V4 = '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8'

# Global dictionary to hold user logs
user_logs = {}
user_data = {} # 
user_states = {} # Variable of storing temporarily state of each user
user_token = {} # Variable of storing token address to buy/sell for each user
portfolio_list = {} # Variable of storing portfolio depending address for each user
temp_priv_key = {}
order_list = {}
DK_list = {}
batch_token = {} # token, amount, count, time
limit_order_threads = {}
current_view_option = {}
preset_list = {}
scanner_list = []

# Global states
IMPORT_NEW_ACCOUNT = "IMPORT_NEW_ACCOUNT"
IMPORT_NEW_ACCOUNT_SOLFARE = "IMPORT_NEW_ACCOUNT_SOLFARE"
SNIPE_TOKEN_ADDRESS = "SNIPE_TOKEN_ADDRESS"
SNIPE_TOKEN_AMOUNT = "SNIPE_TOKEN_AMOUNT"
SWAP_TOKEN_AMOUNT = "SWAP_TOKEN_AMOUNT"
BUY_SELL_TOKEN_ADDRESS = "BUY_SELL_TOKEN_ADDRESS"
CUSTOM_BUY_AMOUNT = "CUSTOM_BUY_AMOUNT"
CUSTOM_SELL_PERCENTAGE = "CUSTOM_SELL_PERCENTAGE"
DELETE_SNIPE_TOKEN = "DELETE_SNIPE_TOKEN"
WITHDRAW_ALL_SOL = "WITHDRAW_ALL_SOL"
WITHDRAW_X_SOL = "WITHDRAW_X_SOL"
INPUT_PASSWORD = "INPUT_PASSWORD"
TX_PASSWORD = "TX_PASSWORD"
BUY_OPTION = "BUY_OPTION"
SELL_OPTION = "SELL_OPTION"
WITHDRAW_ALL_SOL_PASSWORD = "WITHDRAW_ALL_SOL_PASSWORD"
WITHDRAW_X_SOL_PASSWORD = "WITHDRAW_X_SOL_PASSWORD"

BATCH_BUY_AMOUNT = "BATCH_BUY_AMOUNT"
BATCH_BUY_TX_COUNT= "BATCH_BUY_TX_COUNT"
BATCH_BUY_DELAY = "BATCH_BUY_DELAY"

BATCH_SELL_AMOUNT = "BATCH_SELL_AMOUNT"
BATCH_SELL_TX_COUNT= "BATCH_SELL_TX_COUNT"
BATCH_SELL_DELAY = "BATCH_SELL_DELAY"

LOWER_BUY_AMOUNT_PERCENTAGE = "LOWER_BUY_AMOUNT_PERCENTAGE"
LOWER_BUY_PRICE_PERCENTAGE = "LOWER_BUY_PRICE_PERCENTAGE"
LOWER_BUY_AMOUNT_DOLAR = "LOWER_BUY_AMOUNT_DOLAR"

HIGHER_BUY_AMOUNT_PERCENTAGE = "HIGHER_BUY_AMOUNT_PERCENTAGE"
HIGHER_BUY_PRICE_PERCENTAGE = "HIGHER_BUY_PRICE_PERCENTAGE"
HIGHER_BUY_AMOUNT_DOLAR = "HIGHER_BUY_AMOUNT_DOLAR"

STOP_LOSS_AMOUNT_PERCENTAGE = "STOP_LOSS_AMOUNT_PERCENTAGE"
STOP_LOSS_PRICE_PERCENTAGE = "STOP_LOSS_PRICE_PERCENTAGE"
STOP_LOSS_AMOUNT_DOLAR = "STOP_LOSS_AMOUNT_DOLAR"

SELL_PROFIT_AMOUNT_PERCENTAGE = "SELL_PROFIT_AMOUNT_PERCENTAGE"
SELL_PROFIT_PRICE_PERCENTAGE = "SELL_PROFIT_PRICE_PERCENTAGE"
SELL_PROFIT_AMOUNT_DOLAR = "SELL_PROFIT_AMOUNT_DOLAR"

PRESET_PRICE_1="PRESET_PRICE_1"
PRESET_AMOUNT_1="PRESET_AMOUNT_1"
PRESET_PRICE_2="PRESET_PRICE_2"
PRESET_AMOUNT_2="PRESET_AMOUNT_2"
PRESET_PRICE_3="PRESET_PRICE_3"
PRESET_AMOUNT_3="PRESET_AMOUNT_3"
PRESET_PRICE_4="PRESET_PRICE_4"
PRESET_AMOUNT_4="PRESET_AMOUNT_4"